apiVersion: v1
kind: Service
metadata:
  name: internship-service
spec:
  type: NodePort
  selector:
    app: internship-deployment
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000

apiVersion: v1
kind: Service
metadata:
  name: internship-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: internship-deployment
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3000
  - name: https
    port: 443
    protocol: TCP
    targetPort: 3000
